version: '3'

services:
  simulator:
    build: ./app
    command: ["python", "script.py"]
    volumes:
      - ./app:/app

  api:
    build: ./api
    command: python -u api.py
    ports:
      - "5000:5000"
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=pass
      - DB_AUTH_SOURCE=admin
    volumes:
      - ./api:/api
    depends_on:
      - db
      - simulator

  db:
    image: mongo:latest
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_DATABASE=animal_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    ports:
      - 27017:27017
