version: '3'

services:
  simulator:
    build: ./app
    command: ["python", "script.py"]
    volumes:
      - ./app:/app
      - shared-volume:/app/output

  api:
    build: ./api
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=pass
      - DB_AUTH_SOURCE=admin
    volumes:
      - ./api:/api
      - shared-volume:/api/output
    depends_on:
      - db
      - simulator

  db:
    build: ./db
    environment:
      - MONGO_INITDB_DATABASE=animal_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017

volumes:
  shared-volume: